name = "geo-ip-detector"
main = "worker.js"
compatibility_date = "2024-01-01"
account_id = "1df4880142e9b3ccb4341bf7e97c57ff" 

[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.